//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3Part1.ZipCodeFinder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZIPCode", Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    [System.SerializableAttribute()]
    public partial class ZIPCode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment3Part1.ZipCodeFinder.AreaCode[] AreaCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElevationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DayLightSavingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MultiCountyFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Assignment3Part1.ZipCodeFinder.AreaCode[] AreaCodes {
            get {
                return this.AreaCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaCodesField, value) != true)) {
                    this.AreaCodesField = value;
                    this.RaisePropertyChanged("AreaCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CityType {
            get {
                return this.CityTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CityTypeField, value) != true)) {
                    this.CityTypeField = value;
                    this.RaisePropertyChanged("CityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Elevation {
            get {
                return this.ElevationField;
            }
            set {
                if ((object.ReferenceEquals(this.ElevationField, value) != true)) {
                    this.ElevationField = value;
                    this.RaisePropertyChanged("Elevation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TimeZone {
            get {
                return this.TimeZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeZoneField, value) != true)) {
                    this.TimeZoneField = value;
                    this.RaisePropertyChanged("TimeZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DayLightSavings {
            get {
                return this.DayLightSavingsField;
            }
            set {
                if ((object.ReferenceEquals(this.DayLightSavingsField, value) != true)) {
                    this.DayLightSavingsField = value;
                    this.RaisePropertyChanged("DayLightSavings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Classification {
            get {
                return this.ClassificationField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassificationField, value) != true)) {
                    this.ClassificationField = value;
                    this.RaisePropertyChanged("Classification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string MultiCountyFlag {
            get {
                return this.MultiCountyFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.MultiCountyFlagField, value) != true)) {
                    this.MultiCountyFlagField = value;
                    this.RaisePropertyChanged("MultiCountyFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AreaCode", Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    [System.SerializableAttribute()]
    public partial class AreaCode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/", ConfigurationName="ZipCodeFinder.ZipCodeLookupSoap")]
    public interface ZipCodeLookupSoap {
        
        // CODEGEN: Generating message contract since element name ZIPCode from namespace http://malaikaconsultants.com/ZipCodeWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://malaikaconsultants.com/ZipCodeWebService/GetZIPCodeInformation", ReplyAction="*")]
        Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationResponse GetZIPCodeInformation(Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://malaikaconsultants.com/ZipCodeWebService/GetZIPCodeInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationResponse> GetZIPCodeInformationAsync(Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequest request);
        
        // CODEGEN: Generating message contract since element name City from namespace http://malaikaconsultants.com/ZipCodeWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://malaikaconsultants.com/ZipCodeWebService/GetZIPCodeForCityState", ReplyAction="*")]
        Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateResponse GetZIPCodeForCityState(Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://malaikaconsultants.com/ZipCodeWebService/GetZIPCodeForCityState", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateResponse> GetZIPCodeForCityStateAsync(Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequest request);
        
        // CODEGEN: Generating message contract since element name State from namespace http://malaikaconsultants.com/ZipCodeWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://malaikaconsultants.com/ZipCodeWebService/GetAllZIPCodesForState", ReplyAction="*")]
        Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateResponse GetAllZIPCodesForState(Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://malaikaconsultants.com/ZipCodeWebService/GetAllZIPCodesForState", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateResponse> GetAllZIPCodesForStateAsync(Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequest request);
        
        // CODEGEN: Generating message contract since element name Latitude from namespace http://malaikaconsultants.com/ZipCodeWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://malaikaconsultants.com/ZipCodeWebService/GetZIPCodeForLatitudeLongitude", ReplyAction="*")]
        Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeResponse GetZIPCodeForLatitudeLongitude(Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://malaikaconsultants.com/ZipCodeWebService/GetZIPCodeForLatitudeLongitude", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeResponse> GetZIPCodeForLatitudeLongitudeAsync(Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequest request);
        
        // CODEGEN: Generating message contract since element name ZIPCode from namespace http://malaikaconsultants.com/ZipCodeWebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://malaikaconsultants.com/ZipCodeWebService/GetAllAreaCodesForZIPCode", ReplyAction="*")]
        Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeResponse GetAllAreaCodesForZIPCode(Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://malaikaconsultants.com/ZipCodeWebService/GetAllAreaCodesForZIPCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeResponse> GetAllAreaCodesForZIPCodeAsync(Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZIPCodeInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZIPCodeInformation", Namespace="http://malaikaconsultants.com/ZipCodeWebService/", Order=0)]
        public Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequestBody Body;
        
        public GetZIPCodeInformationRequest() {
        }
        
        public GetZIPCodeInformationRequest(Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    public partial class GetZIPCodeInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZIPCode;
        
        public GetZIPCodeInformationRequestBody() {
        }
        
        public GetZIPCodeInformationRequestBody(string ZIPCode) {
            this.ZIPCode = ZIPCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZIPCodeInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZIPCodeInformationResponse", Namespace="http://malaikaconsultants.com/ZipCodeWebService/", Order=0)]
        public Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationResponseBody Body;
        
        public GetZIPCodeInformationResponse() {
        }
        
        public GetZIPCodeInformationResponse(Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    public partial class GetZIPCodeInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment3Part1.ZipCodeFinder.ZIPCode[] GetZIPCodeInformationResult;
        
        public GetZIPCodeInformationResponseBody() {
        }
        
        public GetZIPCodeInformationResponseBody(Assignment3Part1.ZipCodeFinder.ZIPCode[] GetZIPCodeInformationResult) {
            this.GetZIPCodeInformationResult = GetZIPCodeInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZIPCodeForCityStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZIPCodeForCityState", Namespace="http://malaikaconsultants.com/ZipCodeWebService/", Order=0)]
        public Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequestBody Body;
        
        public GetZIPCodeForCityStateRequest() {
        }
        
        public GetZIPCodeForCityStateRequest(Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    public partial class GetZIPCodeForCityStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string City;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string State;
        
        public GetZIPCodeForCityStateRequestBody() {
        }
        
        public GetZIPCodeForCityStateRequestBody(string City, string State) {
            this.City = City;
            this.State = State;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZIPCodeForCityStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZIPCodeForCityStateResponse", Namespace="http://malaikaconsultants.com/ZipCodeWebService/", Order=0)]
        public Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateResponseBody Body;
        
        public GetZIPCodeForCityStateResponse() {
        }
        
        public GetZIPCodeForCityStateResponse(Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    public partial class GetZIPCodeForCityStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment3Part1.ZipCodeFinder.ZIPCode[] GetZIPCodeForCityStateResult;
        
        public GetZIPCodeForCityStateResponseBody() {
        }
        
        public GetZIPCodeForCityStateResponseBody(Assignment3Part1.ZipCodeFinder.ZIPCode[] GetZIPCodeForCityStateResult) {
            this.GetZIPCodeForCityStateResult = GetZIPCodeForCityStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllZIPCodesForStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllZIPCodesForState", Namespace="http://malaikaconsultants.com/ZipCodeWebService/", Order=0)]
        public Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequestBody Body;
        
        public GetAllZIPCodesForStateRequest() {
        }
        
        public GetAllZIPCodesForStateRequest(Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    public partial class GetAllZIPCodesForStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string State;
        
        public GetAllZIPCodesForStateRequestBody() {
        }
        
        public GetAllZIPCodesForStateRequestBody(string State) {
            this.State = State;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllZIPCodesForStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllZIPCodesForStateResponse", Namespace="http://malaikaconsultants.com/ZipCodeWebService/", Order=0)]
        public Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateResponseBody Body;
        
        public GetAllZIPCodesForStateResponse() {
        }
        
        public GetAllZIPCodesForStateResponse(Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    public partial class GetAllZIPCodesForStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment3Part1.ZipCodeFinder.ZIPCode[] GetAllZIPCodesForStateResult;
        
        public GetAllZIPCodesForStateResponseBody() {
        }
        
        public GetAllZIPCodesForStateResponseBody(Assignment3Part1.ZipCodeFinder.ZIPCode[] GetAllZIPCodesForStateResult) {
            this.GetAllZIPCodesForStateResult = GetAllZIPCodesForStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZIPCodeForLatitudeLongitudeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZIPCodeForLatitudeLongitude", Namespace="http://malaikaconsultants.com/ZipCodeWebService/", Order=0)]
        public Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequestBody Body;
        
        public GetZIPCodeForLatitudeLongitudeRequest() {
        }
        
        public GetZIPCodeForLatitudeLongitudeRequest(Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    public partial class GetZIPCodeForLatitudeLongitudeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Longitude;
        
        public GetZIPCodeForLatitudeLongitudeRequestBody() {
        }
        
        public GetZIPCodeForLatitudeLongitudeRequestBody(string Latitude, string Longitude) {
            this.Latitude = Latitude;
            this.Longitude = Longitude;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZIPCodeForLatitudeLongitudeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZIPCodeForLatitudeLongitudeResponse", Namespace="http://malaikaconsultants.com/ZipCodeWebService/", Order=0)]
        public Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeResponseBody Body;
        
        public GetZIPCodeForLatitudeLongitudeResponse() {
        }
        
        public GetZIPCodeForLatitudeLongitudeResponse(Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    public partial class GetZIPCodeForLatitudeLongitudeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment3Part1.ZipCodeFinder.ZIPCode[] GetZIPCodeForLatitudeLongitudeResult;
        
        public GetZIPCodeForLatitudeLongitudeResponseBody() {
        }
        
        public GetZIPCodeForLatitudeLongitudeResponseBody(Assignment3Part1.ZipCodeFinder.ZIPCode[] GetZIPCodeForLatitudeLongitudeResult) {
            this.GetZIPCodeForLatitudeLongitudeResult = GetZIPCodeForLatitudeLongitudeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAreaCodesForZIPCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAreaCodesForZIPCode", Namespace="http://malaikaconsultants.com/ZipCodeWebService/", Order=0)]
        public Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequestBody Body;
        
        public GetAllAreaCodesForZIPCodeRequest() {
        }
        
        public GetAllAreaCodesForZIPCodeRequest(Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    public partial class GetAllAreaCodesForZIPCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZIPCode;
        
        public GetAllAreaCodesForZIPCodeRequestBody() {
        }
        
        public GetAllAreaCodesForZIPCodeRequestBody(string ZIPCode) {
            this.ZIPCode = ZIPCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAreaCodesForZIPCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAreaCodesForZIPCodeResponse", Namespace="http://malaikaconsultants.com/ZipCodeWebService/", Order=0)]
        public Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeResponseBody Body;
        
        public GetAllAreaCodesForZIPCodeResponse() {
        }
        
        public GetAllAreaCodesForZIPCodeResponse(Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://malaikaconsultants.com/ZipCodeWebService/")]
    public partial class GetAllAreaCodesForZIPCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment3Part1.ZipCodeFinder.ZIPCode GetAllAreaCodesForZIPCodeResult;
        
        public GetAllAreaCodesForZIPCodeResponseBody() {
        }
        
        public GetAllAreaCodesForZIPCodeResponseBody(Assignment3Part1.ZipCodeFinder.ZIPCode GetAllAreaCodesForZIPCodeResult) {
            this.GetAllAreaCodesForZIPCodeResult = GetAllAreaCodesForZIPCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZipCodeLookupSoapChannel : Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZipCodeLookupSoapClient : System.ServiceModel.ClientBase<Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap>, Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap {
        
        public ZipCodeLookupSoapClient() {
        }
        
        public ZipCodeLookupSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZipCodeLookupSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipCodeLookupSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipCodeLookupSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationResponse Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap.GetZIPCodeInformation(Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequest request) {
            return base.Channel.GetZIPCodeInformation(request);
        }
        
        public Assignment3Part1.ZipCodeFinder.ZIPCode[] GetZIPCodeInformation(string ZIPCode) {
            Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequest inValue = new Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequest();
            inValue.Body = new Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequestBody();
            inValue.Body.ZIPCode = ZIPCode;
            Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationResponse retVal = ((Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap)(this)).GetZIPCodeInformation(inValue);
            return retVal.Body.GetZIPCodeInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationResponse> Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap.GetZIPCodeInformationAsync(Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequest request) {
            return base.Channel.GetZIPCodeInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationResponse> GetZIPCodeInformationAsync(string ZIPCode) {
            Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequest inValue = new Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequest();
            inValue.Body = new Assignment3Part1.ZipCodeFinder.GetZIPCodeInformationRequestBody();
            inValue.Body.ZIPCode = ZIPCode;
            return ((Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap)(this)).GetZIPCodeInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateResponse Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap.GetZIPCodeForCityState(Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequest request) {
            return base.Channel.GetZIPCodeForCityState(request);
        }
        
        public Assignment3Part1.ZipCodeFinder.ZIPCode[] GetZIPCodeForCityState(string City, string State) {
            Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequest inValue = new Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequest();
            inValue.Body = new Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequestBody();
            inValue.Body.City = City;
            inValue.Body.State = State;
            Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateResponse retVal = ((Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap)(this)).GetZIPCodeForCityState(inValue);
            return retVal.Body.GetZIPCodeForCityStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateResponse> Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap.GetZIPCodeForCityStateAsync(Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequest request) {
            return base.Channel.GetZIPCodeForCityStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateResponse> GetZIPCodeForCityStateAsync(string City, string State) {
            Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequest inValue = new Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequest();
            inValue.Body = new Assignment3Part1.ZipCodeFinder.GetZIPCodeForCityStateRequestBody();
            inValue.Body.City = City;
            inValue.Body.State = State;
            return ((Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap)(this)).GetZIPCodeForCityStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateResponse Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap.GetAllZIPCodesForState(Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequest request) {
            return base.Channel.GetAllZIPCodesForState(request);
        }
        
        public Assignment3Part1.ZipCodeFinder.ZIPCode[] GetAllZIPCodesForState(string State) {
            Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequest inValue = new Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequest();
            inValue.Body = new Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequestBody();
            inValue.Body.State = State;
            Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateResponse retVal = ((Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap)(this)).GetAllZIPCodesForState(inValue);
            return retVal.Body.GetAllZIPCodesForStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateResponse> Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap.GetAllZIPCodesForStateAsync(Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequest request) {
            return base.Channel.GetAllZIPCodesForStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateResponse> GetAllZIPCodesForStateAsync(string State) {
            Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequest inValue = new Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequest();
            inValue.Body = new Assignment3Part1.ZipCodeFinder.GetAllZIPCodesForStateRequestBody();
            inValue.Body.State = State;
            return ((Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap)(this)).GetAllZIPCodesForStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeResponse Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap.GetZIPCodeForLatitudeLongitude(Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequest request) {
            return base.Channel.GetZIPCodeForLatitudeLongitude(request);
        }
        
        public Assignment3Part1.ZipCodeFinder.ZIPCode[] GetZIPCodeForLatitudeLongitude(string Latitude, string Longitude) {
            Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequest inValue = new Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequest();
            inValue.Body = new Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequestBody();
            inValue.Body.Latitude = Latitude;
            inValue.Body.Longitude = Longitude;
            Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeResponse retVal = ((Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap)(this)).GetZIPCodeForLatitudeLongitude(inValue);
            return retVal.Body.GetZIPCodeForLatitudeLongitudeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeResponse> Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap.GetZIPCodeForLatitudeLongitudeAsync(Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequest request) {
            return base.Channel.GetZIPCodeForLatitudeLongitudeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeResponse> GetZIPCodeForLatitudeLongitudeAsync(string Latitude, string Longitude) {
            Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequest inValue = new Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequest();
            inValue.Body = new Assignment3Part1.ZipCodeFinder.GetZIPCodeForLatitudeLongitudeRequestBody();
            inValue.Body.Latitude = Latitude;
            inValue.Body.Longitude = Longitude;
            return ((Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap)(this)).GetZIPCodeForLatitudeLongitudeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeResponse Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap.GetAllAreaCodesForZIPCode(Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequest request) {
            return base.Channel.GetAllAreaCodesForZIPCode(request);
        }
        
        public Assignment3Part1.ZipCodeFinder.ZIPCode GetAllAreaCodesForZIPCode(string ZIPCode) {
            Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequest inValue = new Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequest();
            inValue.Body = new Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequestBody();
            inValue.Body.ZIPCode = ZIPCode;
            Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeResponse retVal = ((Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap)(this)).GetAllAreaCodesForZIPCode(inValue);
            return retVal.Body.GetAllAreaCodesForZIPCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeResponse> Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap.GetAllAreaCodesForZIPCodeAsync(Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequest request) {
            return base.Channel.GetAllAreaCodesForZIPCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeResponse> GetAllAreaCodesForZIPCodeAsync(string ZIPCode) {
            Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequest inValue = new Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequest();
            inValue.Body = new Assignment3Part1.ZipCodeFinder.GetAllAreaCodesForZIPCodeRequestBody();
            inValue.Body.ZIPCode = ZIPCode;
            return ((Assignment3Part1.ZipCodeFinder.ZipCodeLookupSoap)(this)).GetAllAreaCodesForZIPCodeAsync(inValue);
        }
    }
}
